/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sigei.View.MenuAdmin;

import com.sigei.Controller.MenuAdminController;
import com.sigei.View.LoginForm;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author gabri
 */
public class MenuAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuAdmin() {
        initComponents();
        carregarInformacoesGerais();
    }



    private void carregarInformacoesGerais() {

        try {
            int eventosNaoFinalizados  = new MenuAdminController().getEventosNFinalizados();
            int iscricoesAtivas = new MenuAdminController().getIscricoesAtivas();

            eventosAtivos.setText("Eventos ativos: " + eventosNaoFinalizados);
            ParticipantesInscritos.setText("Participantes inscritos:: " + iscricoesAtivas);
            
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar-se com o banco!");
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        TextoSigei = new javax.swing.JLabel();
        BotaoSair = new javax.swing.JLabel();
        jPInformaçoesGerais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ParticipantesInscritos = new javax.swing.JLabel();
        eventosAtivos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        GerenciarUsuarioBotao = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        GerenciarEventosBotao = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(237, 242, 247));

        jPanel4.setBackground(new java.awt.Color(45, 55, 72));

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon.png"))); // NOI18N

        TextoSigei.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        TextoSigei.setForeground(new java.awt.Color(255, 121, 0));
        TextoSigei.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoSigei.setText("SIGEI");

        BotaoSair.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        BotaoSair.setForeground(new java.awt.Color(255, 121, 0));
        BotaoSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout.png"))); // NOI18N
        BotaoSair.setText("Sair");
        BotaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TextoSigei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(65, 65, 65))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TextoSigei)
                .addGap(18, 18, 18)
                .addComponent(Icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(BotaoSair)
                .addGap(47, 47, 47))
        );

        jPInformaçoesGerais.setBackground(new java.awt.Color(223, 234, 245));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Informações Gerais");

        ParticipantesInscritos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ParticipantesInscritos.setForeground(new java.awt.Color(0, 0, 0));
        ParticipantesInscritos.setText("Participantes inscritos:");

        eventosAtivos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        eventosAtivos.setForeground(new java.awt.Color(0, 0, 0));
        eventosAtivos.setText("Eventos ativos:");

        javax.swing.GroupLayout jPInformaçoesGeraisLayout = new javax.swing.GroupLayout(jPInformaçoesGerais);
        jPInformaçoesGerais.setLayout(jPInformaçoesGeraisLayout);
        jPInformaçoesGeraisLayout.setHorizontalGroup(
            jPInformaçoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInformaçoesGeraisLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(143, 143, 143))
            .addGroup(jPInformaçoesGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParticipantesInscritos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPInformaçoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPInformaçoesGeraisLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(eventosAtivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPInformaçoesGeraisLayout.setVerticalGroup(
            jPInformaçoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformaçoesGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(ParticipantesInscritos)
                .addGap(86, 86, 86))
            .addGroup(jPInformaçoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPInformaçoesGeraisLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(eventosAtivos)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(45, 55, 72));

        GerenciarUsuarioBotao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        GerenciarUsuarioBotao.setForeground(new java.awt.Color(255, 121, 0));
        GerenciarUsuarioBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GerenciarUsuarioBotao.setText("Gerenciar Usuarios");
        GerenciarUsuarioBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GerenciarUsuarioBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GerenciarUsuarioBotaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GerenciarUsuarioBotao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GerenciarUsuarioBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(45, 55, 72));

        GerenciarEventosBotao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        GerenciarEventosBotao.setForeground(new java.awt.Color(255, 121, 0));
        GerenciarEventosBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GerenciarEventosBotao.setText("Gerenciar Eventos");
        GerenciarEventosBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GerenciarEventosBotao.setDoubleBuffered(true);
        GerenciarEventosBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GerenciarEventosBotaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GerenciarEventosBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GerenciarEventosBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPInformaçoesGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPInformaçoesGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSairMouseClicked
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_BotaoSairMouseClicked

    private void GerenciarUsuarioBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerenciarUsuarioBotaoMouseClicked
        JFrame tela = new JFrame("Gerenciar Usuários");
        tela.add(new GerenciadorUsuarios());
        tela.pack();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        tela.setResizable(false);
    }//GEN-LAST:event_GerenciarUsuarioBotaoMouseClicked

    private void GerenciarEventosBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerenciarEventosBotaoMouseClicked
        JFrame tela = new JFrame("Gerenciar Eventos");
        tela.add(new GerenciarEventos());
        tela.pack();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        tela.setResizable(false);
    }//GEN-LAST:event_GerenciarEventosBotaoMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotaoSair;
    private javax.swing.JLabel GerenciarEventosBotao;
    private javax.swing.JLabel GerenciarUsuarioBotao;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel ParticipantesInscritos;
    private javax.swing.JLabel TextoSigei;
    private javax.swing.JLabel eventosAtivos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPInformaçoesGerais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
