/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sigei.View.MenuAdmin;

import com.sigei.Controller.MenuAdminController;
import com.sigei.model.evento.Evento;
import com.sigei.model.usuarios.Organizador;

import java.time.format.DateTimeFormatter;

/**
 *
 * @author gabri
 */
public class RelatorioEvento extends javax.swing.JPanel {

    /**
     * Creates new form RelatorioEvento
     */
    Evento e;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    public RelatorioEvento(Evento e) {
        initComponents();
        this.e=e;
        gerarRelatorio();
    }

    public void gerarRelatorio() {
        Nome.setText(e.getNome());
        TipoEvento.setText("Tipo: " + e.getTipo());
        Palestrante.setText("Palestrante: " + e.getPalestrante());
        DataEvento.setText("Data: " + e.getDataEvento().format(formatter));
        StatusEvento.setText("Status: " + e.getStatusEvento().toString());
        VagasEvento.setText("Vagas: " + e.getVagasOcupadas() +"/"+e.getVagasTotal());
        LocalEvento.setText("Local: " + e.getLocal());

        Organizador o = e.getOrganizador();

        NomeOrg.setText("Nome: " + o.getNome());
        EmailOrg.setText("Email: " + o.getEmail());
        EmpresaOrg.setText("Empresa: " + o.getEmpresa());
        TelefoneOrg.setText("Telefone: " + o.getTelefone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TipoEvento = new javax.swing.JLabel();
        Palestrante = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DataEvento = new javax.swing.JLabel();
        StatusEvento = new javax.swing.JLabel();
        VagasEvento = new javax.swing.JLabel();
        LocalEvento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NomeOrg = new javax.swing.JLabel();
        EmailOrg = new javax.swing.JLabel();
        EmpresaOrg = new javax.swing.JLabel();
        TelefoneOrg = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(237, 242, 247));

        jPanel1.setBackground(new java.awt.Color(45, 55, 72));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 121, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatorio do Evento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        Nome.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Nome.setForeground(new java.awt.Color(0, 0, 0));
        Nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nome.setText("NOME");

        jPanel3.setBackground(new java.awt.Color(237, 242, 247));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TipoEvento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TipoEvento.setForeground(new java.awt.Color(0, 0, 0));
        TipoEvento.setText("Tipo: ");

        Palestrante.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Palestrante.setForeground(new java.awt.Color(0, 0, 0));
        Palestrante.setText("Palestrante:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFORMAÇÕES DO EVENTO");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        DataEvento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DataEvento.setForeground(new java.awt.Color(0, 0, 0));
        DataEvento.setText("Data do Evento:");

        StatusEvento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        StatusEvento.setForeground(new java.awt.Color(0, 0, 0));
        StatusEvento.setText("Status:");

        VagasEvento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        VagasEvento.setForeground(new java.awt.Color(0, 0, 0));
        VagasEvento.setText("Vagas");

        LocalEvento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LocalEvento.setForeground(new java.awt.Color(0, 0, 0));
        LocalEvento.setText("Local:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Palestrante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VagasEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LocalEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DataEvento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(StatusEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TipoEvento)
                .addGap(29, 29, 29)
                .addComponent(Palestrante)
                .addGap(27, 27, 27)
                .addComponent(DataEvento)
                .addGap(26, 26, 26)
                .addComponent(StatusEvento)
                .addGap(26, 26, 26)
                .addComponent(VagasEvento)
                .addGap(18, 18, 18)
                .addComponent(LocalEvento)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(45, 55, 72));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(237, 242, 247));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBackground(new java.awt.Color(237, 242, 247));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Organizador do evento");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        NomeOrg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NomeOrg.setForeground(new java.awt.Color(0, 0, 0));
        NomeOrg.setText("Nome");

        EmailOrg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmailOrg.setForeground(new java.awt.Color(0, 0, 0));
        EmailOrg.setText("Email: ");

        EmpresaOrg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmpresaOrg.setForeground(new java.awt.Color(0, 0, 0));
        EmpresaOrg.setText("Empresa: ");

        TelefoneOrg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TelefoneOrg.setForeground(new java.awt.Color(0, 0, 0));
        TelefoneOrg.setText("Telefone: \n");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelefoneOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpresaOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmailOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(NomeOrg)
                .addGap(35, 35, 35)
                .addComponent(EmailOrg)
                .addGap(46, 46, 46)
                .addComponent(EmpresaOrg)
                .addGap(45, 45, 45)
                .addComponent(TelefoneOrg)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataEvento;
    private javax.swing.JLabel EmailOrg;
    private javax.swing.JLabel EmpresaOrg;
    private javax.swing.JLabel LocalEvento;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel NomeOrg;
    private javax.swing.JLabel Palestrante;
    private javax.swing.JLabel StatusEvento;
    private javax.swing.JLabel TelefoneOrg;
    private javax.swing.JLabel TipoEvento;
    private javax.swing.JLabel VagasEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
