/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sigei.View.LoginRegister;

import javax.swing.*;

/**
 *
 * @author gabri
 */
public class RegisterOrganizadorForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterOrganizadorForm.class.getName());
    private LoginForm loginForm;
    /**
     * Creates new form RegisterOrganizadorForm
     */
    public RegisterOrganizadorForm(LoginForm loginForm) {
        this.loginForm = loginForm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoEmail = new javax.swing.JLabel();
        fieldNome1 = new javax.swing.JTextField();
        bglower = new javax.swing.JPanel();
        bgupper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();
        jLabelmin = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        TextoSenha = new javax.swing.JLabel();
        fieldSenha = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        TextoEmail1 = new javax.swing.JLabel();
        TextoNome = new javax.swing.JLabel();
        fieldNome2 = new javax.swing.JTextField();
        TextoEmpresa = new javax.swing.JLabel();
        fieldEmpresa = new javax.swing.JTextField();
        TextoTelefone = new javax.swing.JLabel();
        fieldTelefone = new javax.swing.JTextField();

        TextoEmail.setBackground(new java.awt.Color(237, 242, 247));
        TextoEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoEmail.setForeground(new java.awt.Color(237, 242, 247));
        TextoEmail.setText("Email:");

        fieldNome1.setBackground(new java.awt.Color(74, 85, 104));
        fieldNome1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldNome1.setForeground(new java.awt.Color(247, 250, 252));
        fieldNome1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bglower.setBackground(new java.awt.Color(45, 55, 72));

        bgupper.setBackground(new java.awt.Color(237, 242, 247));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Register Organizador");

        jLabelBack.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabelBack.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack.setText("←");
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });

        jLabelmin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelmin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmin.setText("-");
        jLabelmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgupperLayout = new javax.swing.GroupLayout(bgupper);
        bgupper.setLayout(bgupperLayout);
        bgupperLayout.setHorizontalGroup(
            bgupperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgupperLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jLabelmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelBack)
                .addGap(16, 16, 16))
        );
        bgupperLayout.setVerticalGroup(
            bgupperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgupperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgupperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelmin, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        fieldNome.setBackground(new java.awt.Color(74, 85, 104));
        fieldNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldNome.setForeground(new java.awt.Color(247, 250, 252));
        fieldNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextoSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoSenha.setForeground(new java.awt.Color(237, 242, 247));
        TextoSenha.setText("Senha:");

        fieldSenha.setBackground(new java.awt.Color(74, 85, 104));
        fieldSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldSenha.setForeground(new java.awt.Color(247, 250, 252));
        fieldSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSenhaActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(49, 130, 206));
        LoginButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(237, 242, 247));
        LoginButton.setText("Register");
        LoginButton.setBorder(null);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        TextoEmail1.setBackground(new java.awt.Color(237, 242, 247));
        TextoEmail1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoEmail1.setForeground(new java.awt.Color(237, 242, 247));
        TextoEmail1.setText("Email:");

        TextoNome.setBackground(new java.awt.Color(237, 242, 247));
        TextoNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoNome.setForeground(new java.awt.Color(237, 242, 247));
        TextoNome.setText("Nome");

        fieldNome2.setBackground(new java.awt.Color(74, 85, 104));
        fieldNome2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldNome2.setForeground(new java.awt.Color(247, 250, 252));
        fieldNome2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextoEmpresa.setBackground(new java.awt.Color(237, 242, 247));
        TextoEmpresa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoEmpresa.setForeground(new java.awt.Color(237, 242, 247));
        TextoEmpresa.setText("Empresa:");

        fieldEmpresa.setBackground(new java.awt.Color(74, 85, 104));
        fieldEmpresa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldEmpresa.setForeground(new java.awt.Color(247, 250, 252));
        fieldEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextoTelefone.setBackground(new java.awt.Color(237, 242, 247));
        TextoTelefone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoTelefone.setForeground(new java.awt.Color(237, 242, 247));
        TextoTelefone.setText("Telefone:");

        fieldTelefone.setBackground(new java.awt.Color(74, 85, 104));
        fieldTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldTelefone.setForeground(new java.awt.Color(247, 250, 252));
        fieldTelefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout bglowerLayout = new javax.swing.GroupLayout(bglower);
        bglower.setLayout(bglowerLayout);
        bglowerLayout.setHorizontalGroup(
            bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgupper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bglowerLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bglowerLayout.createSequentialGroup()
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bglowerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bglowerLayout.createSequentialGroup()
                                .addComponent(TextoEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bglowerLayout.createSequentialGroup()
                                .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bglowerLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoSenha)
                            .addComponent(TextoEmpresa)
                            .addComponent(TextoTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        bglowerLayout.setVerticalGroup(
            bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bglowerLayout.createSequentialGroup()
                .addComponent(bgupper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoSenha))
                .addGap(18, 18, 18)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bglower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bglower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
            this.setVisible(false);
    loginForm.setVisible(true);
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelminMouseClicked

    private void fieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSenhaActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new RegisterOrganizadorForm(this).setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel TextoEmail;
    private javax.swing.JLabel TextoEmail1;
    private javax.swing.JLabel TextoEmpresa;
    private javax.swing.JLabel TextoNome;
    private javax.swing.JLabel TextoSenha;
    private javax.swing.JLabel TextoTelefone;
    private javax.swing.JPanel bglower;
    private javax.swing.JPanel bgupper;
    private javax.swing.JTextField fieldEmpresa;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldNome1;
    private javax.swing.JTextField fieldNome2;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JTextField fieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelmin;
    // End of variables declaration//GEN-END:variables
}
