/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sigei.View.LoginRegister;

import javax.swing.JFrame;

/**
 *
 * @author gabri
 */
public class RegisterParticipanteForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterParticipanteForm.class.getName());
    private LoginForm loginForm;
    /**
     * Creates new form RegisterParticipanteForm
     */
    public RegisterParticipanteForm(LoginForm loginForm) {
        this.loginForm = loginForm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bglower2 = new javax.swing.JPanel();
        bgupper2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelBack2 = new javax.swing.JLabel();
        jLabelmin2 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        TextoSenha = new javax.swing.JLabel();
        fieldSenha = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        TextoEmail1 = new javax.swing.JLabel();
        TextoNome = new javax.swing.JLabel();
        fieldNome2 = new javax.swing.JTextField();
        TextoCPF = new javax.swing.JLabel();
        fieldCpf = new javax.swing.JTextField();
        TextoTelefone = new javax.swing.JLabel();
        fieldTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bglower2.setBackground(new java.awt.Color(45, 55, 72));

        bgupper2.setBackground(new java.awt.Color(237, 242, 247));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Register Participante");

        jLabelBack2.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabelBack2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBack2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack2.setText("←");
        jLabelBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBack2MouseClicked(evt);
            }
        });

        jLabelmin2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelmin2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelmin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmin2.setText("-");
        jLabelmin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmin2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgupper2Layout = new javax.swing.GroupLayout(bgupper2);
        bgupper2.setLayout(bgupper2Layout);
        bgupper2Layout.setHorizontalGroup(
            bgupper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgupper2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabelmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelBack2)
                .addGap(16, 16, 16))
        );
        bgupper2Layout.setVerticalGroup(
            bgupper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgupper2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgupper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        fieldNome.setBackground(new java.awt.Color(74, 85, 104));
        fieldNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldNome.setForeground(new java.awt.Color(247, 250, 252));
        fieldNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextoSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoSenha.setForeground(new java.awt.Color(237, 242, 247));
        TextoSenha.setText("Senha:");

        fieldSenha.setBackground(new java.awt.Color(74, 85, 104));
        fieldSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldSenha.setForeground(new java.awt.Color(247, 250, 252));
        fieldSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSenhaActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(49, 130, 206));
        LoginButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(237, 242, 247));
        LoginButton.setText("Register");
        LoginButton.setBorder(null);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        TextoEmail1.setBackground(new java.awt.Color(237, 242, 247));
        TextoEmail1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoEmail1.setForeground(new java.awt.Color(237, 242, 247));
        TextoEmail1.setText("Email:");

        TextoNome.setBackground(new java.awt.Color(237, 242, 247));
        TextoNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoNome.setForeground(new java.awt.Color(237, 242, 247));
        TextoNome.setText("Nome");

        fieldNome2.setBackground(new java.awt.Color(74, 85, 104));
        fieldNome2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldNome2.setForeground(new java.awt.Color(247, 250, 252));
        fieldNome2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextoCPF.setBackground(new java.awt.Color(237, 242, 247));
        TextoCPF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoCPF.setForeground(new java.awt.Color(237, 242, 247));
        TextoCPF.setText("CPF:");

        fieldCpf.setBackground(new java.awt.Color(74, 85, 104));
        fieldCpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldCpf.setForeground(new java.awt.Color(247, 250, 252));
        fieldCpf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCpfActionPerformed(evt);
            }
        });

        TextoTelefone.setBackground(new java.awt.Color(237, 242, 247));
        TextoTelefone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoTelefone.setForeground(new java.awt.Color(237, 242, 247));
        TextoTelefone.setText("Telefone:");

        fieldTelefone.setBackground(new java.awt.Color(74, 85, 104));
        fieldTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldTelefone.setForeground(new java.awt.Color(247, 250, 252));
        fieldTelefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout bglower2Layout = new javax.swing.GroupLayout(bglower2);
        bglower2.setLayout(bglower2Layout);
        bglower2Layout.setHorizontalGroup(
            bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgupper2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bglower2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bglower2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextoSenha)
                    .addComponent(TextoTelefone)
                    .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCPF))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bglower2Layout.setVerticalGroup(
            bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bglower2Layout.createSequentialGroup()
                .addComponent(bgupper2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoSenha))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bglower2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bglower2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBack2MouseClicked
        this.setVisible(false);
        loginForm.setVisible(true);
    }//GEN-LAST:event_jLabelBack2MouseClicked

    private void jLabelmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmin2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelmin2MouseClicked

    private void fieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSenhaActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new RegisterParticipanteForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel TextoCPF;
    private javax.swing.JLabel TextoEmail1;
    private javax.swing.JLabel TextoNome;
    private javax.swing.JLabel TextoSenha;
    private javax.swing.JLabel TextoTelefone;
    private javax.swing.JPanel bglower2;
    private javax.swing.JPanel bgupper2;
    private javax.swing.JTextField fieldCpf;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldNome2;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JTextField fieldTelefone;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBack2;
    private javax.swing.JLabel jLabelmin2;
    // End of variables declaration//GEN-END:variables
}
