/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sigei.View;

import com.sigei.Controller.LoginController;
import com.sigei.View.MenuAdmin.MenuAdmin;
import com.sigei.View.MenuOrganizador.MenuOrgaizador;
import com.sigei.View.MenuParticipante.MenuPaticipante;
import com.sigei.View.Register.RegisterOrganizador;
import com.sigei.View.Register.RegisterParticipante;
import com.sigei.model.usuarios.Usuario;

import javax.swing.*;
import java.awt.event.MouseEvent;


/**
 *
 * @author gabri
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        RegisterButton1 = new javax.swing.JLabel();
        bglower = new javax.swing.JPanel();
        bgupper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextoEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        TextoSenha = new javax.swing.JLabel();
        fieldSenha = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        RegisterButtonParticipante = new javax.swing.JLabel();
        RegisterButtonOrganizador = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        RegisterButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RegisterButton1.setForeground(new java.awt.Color(190, 227, 248));
        RegisterButton1.setText("Create new account");
        RegisterButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterButton1MouseEntered(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bglower.setBackground(new java.awt.Color(45, 55, 72));

        bgupper.setBackground(new java.awt.Color(237, 242, 247));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login SIGEI");

        javax.swing.GroupLayout bgupperLayout = new javax.swing.GroupLayout(bgupper);
        bgupper.setLayout(bgupperLayout);
        bgupperLayout.setHorizontalGroup(
            bgupperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgupperLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        bgupperLayout.setVerticalGroup(
            bgupperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgupperLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        TextoEmail.setBackground(new java.awt.Color(237, 242, 247));
        TextoEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoEmail.setForeground(new java.awt.Color(237, 242, 247));
        TextoEmail.setText("Email:");

        fieldEmail.setBackground(new java.awt.Color(74, 85, 104));
        fieldEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldEmail.setForeground(new java.awt.Color(247, 250, 252));
        fieldEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });

        TextoSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoSenha.setForeground(new java.awt.Color(237, 242, 247));
        TextoSenha.setText("Senha:");

        fieldSenha.setBackground(new java.awt.Color(74, 85, 104));
        fieldSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldSenha.setForeground(new java.awt.Color(247, 250, 252));
        fieldSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSenhaActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(49, 130, 206));
        LoginButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(237, 242, 247));
        LoginButton.setText("Login");
        LoginButton.setBorder(null);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        RegisterButtonParticipante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RegisterButtonParticipante.setForeground(new java.awt.Color(190, 227, 248));
        RegisterButtonParticipante.setText("Registrar Participante");
        RegisterButtonParticipante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButtonParticipante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonParticipanteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterButtonParticipanteMouseEntered(evt);
            }
        });

        RegisterButtonOrganizador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RegisterButtonOrganizador.setForeground(new java.awt.Color(190, 227, 248));
        RegisterButtonOrganizador.setText("Registrar Organizador");
        RegisterButtonOrganizador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButtonOrganizador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonOrganizadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterButtonOrganizadorMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout bglowerLayout = new javax.swing.GroupLayout(bglower);
        bglower.setLayout(bglowerLayout);
        bglowerLayout.setHorizontalGroup(
            bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgupper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bglowerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bglowerLayout.createSequentialGroup()
                        .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(fieldSenha))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(bglowerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RegisterButtonParticipante)
                        .addGap(37, 37, 37)
                        .addComponent(RegisterButtonOrganizador)
                        .addGap(57, 57, 57))))
            .addGroup(bglowerLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bglowerLayout.setVerticalGroup(
            bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bglowerLayout.createSequentialGroup()
                .addComponent(bgupper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoSenha))
                .addGap(60, 60, 60)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(bglowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButtonParticipante)
                    .addComponent(RegisterButtonOrganizador))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bglower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bglower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSenhaActionPerformed

    private void RegisterButtonParticipanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonParticipanteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonParticipanteMouseEntered

    private void RegisterButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButton1MouseEntered

    private void RegisterButtonOrganizadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonOrganizadorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonOrganizadorMouseEntered

    private void RegisterButtonParticipanteMouseClicked(MouseEvent evt) {
        JFrame frame = new JFrame("Registrar Participante");
        RegisterParticipante rp = new RegisterParticipante();
        frame.add(rp);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(this);

        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                LoginForm.this.setVisible(true);
            }
        });

        frame.setVisible(true);
        this.setVisible(false);
    }                                                       

    private void RegisterButtonOrganizadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonOrganizadorMouseClicked
        JFrame frame = new JFrame("Registrar Organizador");
        RegisterOrganizador rp = new RegisterOrganizador();
        frame.add(rp);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(this);

        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                LoginForm.this.setVisible(true);
            }
        });
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegisterButtonOrganizadorMouseClicked

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String email = fieldEmail.getText();
        String senha = new String(fieldSenha.getPassword());

        try {
            Usuario u = new LoginController().autenticar(email, senha);
            JOptionPane.showMessageDialog(this, "Bem-Vindo, "+u.getNome() + "!");
            int i = new LoginController().tipoUsuario(u);

            if (i==1) {
                MenuPaticipante menu = new MenuPaticipante();
                menu.setLocationRelativeTo(null); // Centraliza na tela
                menu.setVisible(true);
            }
            if (i==2) {
                MenuOrgaizador menu = new MenuOrgaizador();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }
            if (i==3) {
                MenuAdmin menu = new MenuAdmin();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }

            this.dispose();// Fecha a janela de login
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel RegisterButton1;
    private javax.swing.JLabel RegisterButtonOrganizador;
    private javax.swing.JLabel RegisterButtonParticipante;
    private javax.swing.JLabel TextoEmail;
    private javax.swing.JLabel TextoSenha;
    private javax.swing.JPanel bglower;
    private javax.swing.JPanel bgupper;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
