/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sigei.View.Register;

import com.sigei.Controller.RegisterPartController;
import com.sigei.model.usuarios.Participante;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author gabri
 */
public class RegisterParticipante extends javax.swing.JPanel {

    /**
     * Creates new form RegisterParticipante
     */
    public RegisterParticipante() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bglower2 = new javax.swing.JPanel();
        bgupper3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        TextoSenha = new javax.swing.JLabel();
        fieldSenha = new javax.swing.JPasswordField();
        RegisterButon = new javax.swing.JButton();
        TextoEmail1 = new javax.swing.JLabel();
        TextoNome = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        TextoCPF = new javax.swing.JLabel();
        fieldCpf = new javax.swing.JTextField();
        TextoTelefone = new javax.swing.JLabel();
        fieldTelefone = new javax.swing.JTextField();

        setBackground(new java.awt.Color(45, 55, 72));

        bglower2.setBackground(new java.awt.Color(45, 55, 72));

        bgupper3.setBackground(new java.awt.Color(237, 242, 247));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Register Participante");

        javax.swing.GroupLayout bgupper3Layout = new javax.swing.GroupLayout(bgupper3);
        bgupper3.setLayout(bgupper3Layout);
        bgupper3Layout.setHorizontalGroup(
            bgupper3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgupper3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgupper3Layout.setVerticalGroup(
            bgupper3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgupper3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        fieldNome.setBackground(new java.awt.Color(74, 85, 104));
        fieldNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldNome.setForeground(new java.awt.Color(247, 250, 252));
        fieldNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });

        TextoSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoSenha.setForeground(new java.awt.Color(237, 242, 247));
        TextoSenha.setText("Senha:");

        fieldSenha.setBackground(new java.awt.Color(74, 85, 104));
        fieldSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldSenha.setForeground(new java.awt.Color(247, 250, 252));
        fieldSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSenhaActionPerformed(evt);
            }
        });

        RegisterButon.setBackground(new java.awt.Color(49, 130, 206));
        RegisterButon.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        RegisterButon.setForeground(new java.awt.Color(237, 242, 247));
        RegisterButon.setText("Register");
        RegisterButon.setBorder(null);
        RegisterButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButonActionPerformed(evt);
            }
        });

        TextoEmail1.setBackground(new java.awt.Color(237, 242, 247));
        TextoEmail1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoEmail1.setForeground(new java.awt.Color(237, 242, 247));
        TextoEmail1.setText("Email:");

        TextoNome.setBackground(new java.awt.Color(237, 242, 247));
        TextoNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoNome.setForeground(new java.awt.Color(237, 242, 247));
        TextoNome.setText("Nome");

        fieldEmail.setBackground(new java.awt.Color(74, 85, 104));
        fieldEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldEmail.setForeground(new java.awt.Color(247, 250, 252));
        fieldEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });

        TextoCPF.setBackground(new java.awt.Color(237, 242, 247));
        TextoCPF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoCPF.setForeground(new java.awt.Color(237, 242, 247));
        TextoCPF.setText("CPF:");

        fieldCpf.setBackground(new java.awt.Color(74, 85, 104));
        fieldCpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldCpf.setForeground(new java.awt.Color(247, 250, 252));
        fieldCpf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCpfActionPerformed(evt);
            }
        });

        TextoTelefone.setBackground(new java.awt.Color(237, 242, 247));
        TextoTelefone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextoTelefone.setForeground(new java.awt.Color(237, 242, 247));
        TextoTelefone.setText("Telefone:");

        fieldTelefone.setBackground(new java.awt.Color(74, 85, 104));
        fieldTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldTelefone.setForeground(new java.awt.Color(247, 250, 252));
        fieldTelefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bglower2Layout = new javax.swing.GroupLayout(bglower2);
        bglower2.setLayout(bglower2Layout);
        bglower2Layout.setHorizontalGroup(
            bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgupper3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bglower2Layout.createSequentialGroup()
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bglower2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoSenha)
                            .addComponent(TextoTelefone)
                            .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCPF))
                        .addGap(18, 18, 18)
                        .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bglower2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(RegisterButon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        bglower2Layout.setVerticalGroup(
            bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bglower2Layout.createSequentialGroup()
                .addComponent(bgupper3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoSenha))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bglower2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(RegisterButon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bglower2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bglower2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed

    }//GEN-LAST:event_fieldNomeActionPerformed

    private void fieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSenhaActionPerformed

    }//GEN-LAST:event_fieldSenhaActionPerformed

    private void RegisterButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButonActionPerformed
        String nome = fieldNome.getText();
        String email = fieldEmail.getText();
        String senha = new String(fieldSenha.getPassword());
        String telefone = fieldTelefone.getText();
        String cpf = fieldCpf.getText();

        try {
            Participante p = new Participante(nome,email,senha,telefone, cpf);
            new RegisterPartController().Registrar(p);
            JOptionPane.showMessageDialog(this, "Participante registrado com sucesso!");
            SwingUtilities.getWindowAncestor(this).dispose();// Fecha a janela
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar no banco!");
        }
    }//GEN-LAST:event_RegisterButonActionPerformed

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed

    private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCpfActionPerformed

    }//GEN-LAST:event_fieldCpfActionPerformed

    private void fieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTelefoneActionPerformed

    }//GEN-LAST:event_fieldTelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterButon;
    private javax.swing.JLabel TextoCPF;
    private javax.swing.JLabel TextoEmail1;
    private javax.swing.JLabel TextoNome;
    private javax.swing.JLabel TextoSenha;
    private javax.swing.JLabel TextoTelefone;
    private javax.swing.JPanel bglower2;
    private javax.swing.JPanel bgupper3;
    private javax.swing.JTextField fieldCpf;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JTextField fieldTelefone;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
